import type { AggregatedJob } from "./types"

export function getAggregatedJobSources(targetRole: string): AggregatedJob[] {
  const now = new Date()
  const daysAgo = (days: number) =>
    new Date(now.getTime() - days * 86_400_000).toISOString()
  const daysFromNow = (days: number) =>
    new Date(now.getTime() + days * 86_400_000).toISOString()

  return [
    {
      id: "greenhouse-vanta-1",
      source: "greenhouse",
      sourceUrl: "https://boards.greenhouse.io/vanta/jobs/product-ai",
      title: targetRole,
      company: "Vanta",
      location: "Remote",
      description:
        "Build AI workflow systems with React, TypeScript, analytics, and customer-facing product judgment.",
      salaryMin: 145000,
      salaryMax: 180000,
      currency: "USD",
      recruiterName: "Elena Park",
      recruiterEmail: "elena@vanta.com",
      employmentType: "full-time",
      seniority: "senior",
      skills: ["React", "TypeScript", "AI workflows", "Product Strategy"],
      postedAt: daysAgo(3),
      expiresAt: daysFromNow(28),
      applicantCount: 76,
      isRemote: true,
    },
    {
      id: "lever-vanta-duplicate",
      source: "lever",
      sourceUrl: "https://jobs.lever.co/vanta/product-ai",
      title: targetRole,
      company: "Vanta",
      location: "Remote",
      description: "Duplicate listing for the same AI product role.",
      salaryMin: 145000,
      salaryMax: 180000,
      currency: "USD",
      recruiterName: "Elena Park",
      employmentType: "full-time",
      seniority: "senior",
      skills: ["React", "TypeScript", "Product Strategy"],
      postedAt: daysAgo(4),
      expiresAt: daysFromNow(26),
      applicantCount: 91,
      isRemote: true,
    },
    {
      id: "ashby-linear-1",
      source: "ashby",
      sourceUrl: "https://jobs.ashbyhq.com/linear/ai-workflows",
      title: `${targetRole} Lead`,
      company: "Linear",
      location: "Remote",
      description:
        "Lead job-to-offer product surfaces, dashboard systems, automation, and premium UX.",
      salaryMin: 160000,
      salaryMax: 210000,
      currency: "USD",
      recruiterEmail: "talent@linear.app",
      employmentType: "full-time",
      seniority: "lead",
      skills: ["Product Strategy", "UX", "Automation", "Analytics"],
      postedAt: daysAgo(8),
      expiresAt: daysFromNow(20),
      applicantCount: 132,
      isRemote: true,
    },
    {
      id: "workday-stripe-1",
      source: "workday",
      sourceUrl: "https://stripe.com/jobs/search",
      title: `Senior ${targetRole}`,
      company: "Stripe",
      location: "New York",
      description:
        "Own dashboard quality, applicant intelligence, role matching, and business systems.",
      salaryMin: 155000,
      salaryMax: 195000,
      currency: "USD",
      employmentType: "full-time",
      seniority: "senior",
      skills: ["TypeScript", "Analytics", "Systems Design", "React"],
      postedAt: daysAgo(12),
      expiresAt: daysFromNow(14),
      applicantCount: 210,
      isRemote: false,
    },
    {
      id: "manual-ramp-1",
      source: "manual",
      sourceUrl: "https://ramp.com/careers",
      title: targetRole,
      company: "Ramp",
      location: "Hybrid",
      description:
        "Create high-signal user workflows with resume intelligence and application automation.",
      salaryMin: 130000,
      salaryMax: 170000,
      currency: "USD",
      recruiterName: "Talent Team",
      employmentType: "full-time",
      seniority: "mid",
      skills: ["React", "Product Strategy", "Automation"],
      postedAt: daysAgo(18),
      expiresAt: daysFromNow(9),
      applicantCount: 188,
      isRemote: false,
    },
    {
      id: "fake-job-1",
      source: "manual",
      sourceUrl: "https://example.invalid/fake",
      title: "Remote AI Job No Interview Required",
      company: "Fast Hiring Global",
      location: "Remote",
      description:
        "No interview required. Pay registration fee and apply on WhatsApp for unlimited income.",
      employmentType: "full-time",
      skills: ["AI"],
      postedAt: daysAgo(1),
      isRemote: true,
    },
    {
      id: "expired-job-1",
      source: "greenhouse",
      sourceUrl: "https://boards.greenhouse.io/expired",
      title: targetRole,
      company: "Archive Labs",
      location: "Remote",
      description: "Expired listing retained by source.",
      salaryMin: 120000,
      salaryMax: 150000,
      employmentType: "full-time",
      skills: ["React"],
      postedAt: daysAgo(72),
      expiresAt: daysAgo(7),
      isRemote: true,
    },
  ]
}
